name: Test_GPT
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - matplotlib  
  - numpy=1.23.3
  - pip
  - python=3.9
  - scipy
  - pillow
  - pytorch=2.5.1
  - transformers
  - datasets
  - tiktoken
  - wandb
  - tqdm
  - tabulate
  - graphviz
  - pydot
  - huggingface_hub
  - requests==2.27.1